spring.application.name=service
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=x-dogs-version

spring.threads.virtual.enabled=true